### ISSUE TITLE
无法加载样式表

### ISSUE THREAD

**Issue by ghost** [wa-ri/hexo-theme-ztopic#4]
我直接git下来的放在了theme目录下。可是却加载不出来样式表。请问是什么原因？

**Comment by zo-ly** [comment]
是否安装了sass `$ npm install --save hexo-renderer-sass`

**Comment by ghost** [comment]
**Header of edinburgh theme
menu:
About: /about
Contact: /contact
Instagram: https://www.instagram.com
LinkedIn: https://www.linkedin.com
Facebook: https://www.facebook.com
category: /categories**
原因我找到了，之前在 _config.yml 中有这么一段是之前一个主题使用的。可能是发生了冲突。我把它注释了以后就ok了。谢谢~

**Comment by zo-ly** [comment]
好的，解决了就行
